<a href="https://colab.research.google.com/github/Marquirou/Extraccion_de_conocimiento_DB/blob/main/LAB01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
datos = {
    "usuario" : ["Ana", "Luis", "Martha", "Carolina", "Sofia", "Pedro", "Elena","Diego"],
    "edad" : [22,35,28,40,19,31,24,45],
    "ciudad" : ["CDMX", "Monterrey", "Guadalajara", "Puebla", "Cancún", "Merida", "Tijuana", "Veracruz"],
    "activo" : [True, False, True, True, False, True, False, True],
    "fecha_registro" : ["2026-01-10", "2026-01-12", "2026-01-05", "2026-01-13", "2026-01-11", "2026-01-20", "2026-01-22", "2026-01-17"]
}

In [ ]:
df = pd.DataFrame(datos)

In [ ]:
#Imprime los primeros 5
df.head()

    usuario  edad       ciudad  activo fecha_registro
0       Ana    22         CDMX    True     2026-01-10
1      Luis    35    Monterrey   False     2026-01-12
2    Martha    28  Guadalajara    True     2026-01-05
3  Carolina    40       Puebla    True     2026-01-13
4     Sofia    19       Cancún   False     2026-01-11

In [ ]:
#Crear un DataFrame con 1000000
cantidad = 1000000

In [ ]:
import random

In [ ]:
#Datos aleatorios
nombres = ["Ana", "Luis", "Martha", "Carolina", "Sofía", "Pedro", "Elena", "Diego"]
ciudades = ["CDMX", "Monterrey", "Guadalajara", "Puebla", "Cancún", "Merida", "Tijuana", "Toluca"]
categorias = ["Tecnologías", "Ropa", "Hogar", "Videojuegos", "Deportes", "Calzado", "Cosmeticos", "Infantil"]

In [ ]:
dMilton = pd.DataFrame ({
    "nombre" : [random.choice(nombres) for _ in range(cantidad)],
    "ciudad" : [random.choice(ciudades) for _ in range(cantidad)],
    "categoria" : [random.choice(categorias) for _ in range(cantidad)],
    "edad" : [random.randint(18,70) for _ in range(cantidad)],
    "salario" : [round(random.uniform(5000, 50000), 2) for _ in range (cantidad)],
    "activo" : [random.choice([True,False]) for _ in range(cantidad)],
    "anio_registro" : [random.randint(2020,2026) for _ in range(cantidad)],

})

In [ ]:
dMilton.memory_usage(deep = True)

Index                 132
nombre           56125751
ciudad           57887574
categoria        58991377
edad              8000000
salario           8000000
activo            1000000
anio_registro     8000000
dtype: int64

In [ ]:
dMilton.memory_usage(deep = True).sum() /1024**2

np.float64(188.832124710083)